[project]
name = "jotto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.3",
    "django-htmx>=1.27.0",
    "django-redis>=6.0.0",
    "pytest>=9.0.2",
]

[tool.djlint]
profile = "django"
line_break_after_multiline_tag = true
